export type BaseThemeColorVariable =
  | "--background-global"
  | "--background-secondary"
  | "--background-light"
  | "--background-first-screen-description"
  | "--text-main"
  | "--text-secondary"
  | "--text-light"
  | "--text-thirdary"
  | "--text-button-disabled"
  |"--text-main-screen-title"
  | "--text-main-screen-description"
  | "--text-main-screen-subtitle"
  | "--text-error-bright"
  | "--text-error-light"
  | "--border-main"
  | "--border-error"
  | "--border-placeholder"
  | "--border-button-secondary"
  | "--border-profile-icon"
 | "--profile-button-wave"
  | "--divider-main"
  | "--divider-secondary"
  | "--divider-thirdary"
  | "--progress-bar-default"
  | "--text-tabs"
  | "--background-profile-icon"
  | "--background-button-profile"
    | "--background-button-disabled"

