services:
  # Main service for Traefik (nginx load balancer)
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_PROJECT_NAME=${NEXT_PUBLIC_PROJECT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

    container_name: ${NEXT_PUBLIC_PROJECT_NAME}
    user: "1000:1000"
    environment:
      - NEXT_PUBLIC_PROJECT_NAME=${NEXT_PUBLIC_PROJECT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NODE_ENV=production
      - PORT=${PORT}
    volumes:
      - ./app/data:/usr/src/app/data  
    networks:
      - coex-tma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.tls.certresolver=myresolver"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.service=${TRAEFIK_SERVICE}"

      - "traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=${PORT}"

      # Rate Limit — РАБОТАЕТ!
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-limit.inflightreq.amount=30"

      # Security Headers
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.sslRedirect=true"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.stsPreload=true"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.frameDeny=true"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.${TRAEFIK_SERVICE}-sec.headers.browserXssFilter=true"

      # Применяем
      - "traefik.http.routers.${TRAEFIK_SERVICE}.middlewares=${TRAEFIK_SERVICE}-limit,${TRAEFIK_SERVICE}-sec" 


networks:
  coex-tma:
    external: true