export const ROUTES_NAMES: { [key in string]: string } = {
  "/exchange/details": "Обмен криптовалют: подтверждение введенных данных",
  "/exchange/input": "Обмен криптовалют: ввод данных",
  "/exchange/result": "Обмен криптовалют: статус операции",
  "/exchange/type": "Обмен криптовалют: выбор направления",
  "/faq": "Нас часто спрашивают",
  "/": "Главная",
  "/profile": "Профиль",
  "/profile/request": "Детали операции",
  "/transfer-abroad/details": "Перевод за рубеж: подтверждение введенных данных",
  "/transfer-abroad/input/cards": "Перевод за рубеж: ввод данных - Пополнение зарубежных карт",
  "/transfer-abroad/input/chinese-platforms": "Перевод за рубеж: ввод данных - Alipay и WeChat",
  "/transfer-abroad/input/fta": "Перевод за рубеж: ввод данных - Платежный агент/ВЭД (валюта и задача)",
  "/transfer-abroad/input/fta/requisites-and-license": "Перевод за рубеж: ввод данных - Платежный агент/ВЭД (реквизиты, лицензия и примеры инвойса)",
  "/transfer-abroad/input/invoice": "Перевод за рубеж: ввод данных - Оплата по инвойсу",
  "/transfer-abroad/result": "Перевод за рубеж: статус операции",
  "/transfer-abroad/type": "Перевод за рубеж: выбор типа операции",
};
